name: Release

on:
  push:
    branches:
      - main
    paths:
      - 'VERSION'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: ./src/github.com/${{ github.repository }}
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          path: ./src/github.com/${{ github.repository }}
      - name: Create release
        id: create_release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=$(cat VERSION | tr -d '\n')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Creating release $VERSION"
          gh release create "$VERSION" -R ${{ github.repository }} --title "$VERSION" --generate-notes
